# Deploy docker-consul-haproxy
 - name: create /etc/consul-haproxy
   file:
     path: /etc/consul-haproxy
     state: directory

 - name: copy haproxy template
   copy:
     src: files/haproxy-template.conf
     dest: /etc/consul-haproxy/haproxy-template.conf

 - name: copy consul-haproxy configuration
   copy:
     src: files/consul-haproxy-conf.json
     dest: /etc/consul-haproxy/consul-haproxy-conf.json

 - name: install consul-haproxy
   get_url:
     url: https://github.com/hashicorp/consul-haproxy/releases/download/v0.1.0/consul-haproxy_linux_amd64
     dest: /bin/consul-haproxy
     mode: 0700

 - name: template consul-haproxy.service
   template:
     src: consul-haproxy.service
     dest: /usr/lib/systemd/system/consul-haproxy.service
   register: consul_haproxy_unit
   notify: restart consul-haproxy

 - name: systemctl daemon-reload
   command: /bin/systemctl daemon-reload
   when: consul_haproxy_unit.changed

 - name: enable and start consul-haproxy.service
   service:
     name: consul-haproxy
     enabled: yes
     state: started
